#!/bin/sh
cd ../../

docker stop dev_sakura
docker rm dev_sakura
docker run --rm \
	--name dev_sakura \
	--gpus all \
	--shm-size=70g \
	-v $HOME/.config/sakura/config.yml:/root/.config/sakura/config.yml \
	-v $(pwd)/data:/workspace/data \
	-v $(pwd)/mnist_demo:/workspace/mnist_demo \
	-it zakuroai/sakura python -m mnist_demo
